# Generated by Django 4.2.3 on 2023-08-09 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('accounts', '0002_alter_usercustom_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playList', models.ManyToManyField(to='api.playlist')),
                ('resource', models.ManyToManyField(to='api.resources')),
                ('roadmaps', models.ManyToManyField(to='api.roadmaps')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
