# Generated by Django 4.2.3 on 2023-08-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_track'),
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='track',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.track'),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
